### ISSUE TITLE
Startup warnings

### ISSUE THREAD

**Issue by KIRUYXAN** [darbyjack/PlayerTime#6]
[17:48:48 WARN]: [AutoSaveWorld] Plugin PlayerTime attempted to establish connection https://api.spigotmc.org/legacy/update.php?resource=58915 in main server thread
[17:48:48 WARN]: [AutoSaveWorld] Plugin PlayerTime attempted to establish connection socket://api.spigotmc.org:443 in main server thread

The plugin attempts to establish a connection to the Spigot servers on the main server thread. This can cause lag and delays since the main thread is responsible for processing game events.

[17:48:48 WARN]: Nag author(s): '[blockslayer22]' of 'PlayerTime v1.0.7-RELEASE' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

The plugin uses System.out for console output and optionally System.err for errors. This is a bad practice that makes debugging difficult and can cause performance problems. It is recommended to use the logger provided by Spigot.

**Comment by KIRUYXAN** [comment]
and also 
[20:28:26 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[20:28:26 WARN]:        at PlayerTime-1.0.7-RELEASE.jar//me.rayzr522.jsonmessage.JSONMessage$ReflectionHelper.getVersion(JSONMessage.java:746)
[20:28:26 WARN]:        at PlayerTime-1.0.7-RELEASE.jar//me.rayzr522.jsonmessage.JSONMessage$ReflectionHelper.<clinit>(JSONMessage.java:516)
[20:28:26 WARN]:        at PlayerTime-1.0.7-RELEASE.jar//me.rayzr522.jsonmessage.JSONMessage.send(JSONMessage.java:158)
[20:28:26 WARN]:        at PlayerTime-1.0.7-RELEASE.jar//me.glaremasters.playertime.events.Announcement.lambda$onJoin$0(Announcement.java:36)
[20:28:26 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[20:28:26 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:28:26 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:28:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:28:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:28:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:28:26 WARN]: [PlayerTime] Plugin PlayerTime v1.0.7-RELEASE generated an exception while executing task 229
java.lang.IllegalStateException: ReflectionHelper is not set up!
        at PlayerTime-1.0.7-RELEASE.jar/me.rayzr522.jsonmessage.JSONMessage$ReflectionHelper.createTextPacket(JSONMessage.java:608) ~[PlayerTime-1.0.7-RELEASE.jar:?]
        at PlayerTime-1.0.7-RELEASE.jar/me.rayzr522.jsonmessage.JSONMessage.send(JSONMessage.java:158) ~[PlayerTime-1.0.7-RELEASE.jar:?]
        at PlayerTime-1.0.7-RELEASE.jar/me.glaremasters.playertime.events.Announcement.lambda$onJoin$0(Announcement.java:36) ~[PlayerTime-1.0.7-RELEASE.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-15-2df432f]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-15-2df432f]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

The plugin does not work on my paper 1.21 server

**Comment by KIRUYXAN** [comment]
and also
[19:05:43 WARN]: [PlayerTime] Plugin PlayerTime v1.0.7-RELEASE generated an exception while executing task 1229
java.lang.IllegalStateException: ReflectionHelper is not set up!
        at PlayerTime-1.0.7-RELEASE.jar/me.rayzr522.jsonmessage.JSONMessage$ReflectionHelper.createTextPacket(JSONMessage.java:608) ~[PlayerTime-1.0.7-RELEASE.jar:?]
        at PlayerTime-1.0.7-RELEASE.jar/me.rayzr522.jsonmessage.JSONMessage.send(JSONMessage.java:158) ~[PlayerTime-1.0.7-RELEASE.jar:?]
        at PlayerTime-1.0.7-RELEASE.jar/me.glaremasters.playertime.events.Announcement.lambda$onJoin$0(Announcement.java:36) ~[PlayerTime-1.0.7-RELEASE.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.21.jar:1.21-15-2df432f]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-15-2df432f]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Error java.lang.IllegalStateException: ReflectionHelper is not set up! in the PlayerTime plugin indicates that the ReflectionHelper component used to send JSON messages to players was not initialized correctly.
